services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  restaurant-svc:
    image: lyyhua/restaurant-svc:latest
    build:
      context: .
      dockerfile: src/RestaurantService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=restaurant
      - RabbitMq__Host=rabbitmq
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: lyyhua/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - RestaurantServiceUrl=http://restaurant-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
  order-svc:
    image: lyyhua/order-svc:latest
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__OrderDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    image: lyyhua/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  notify-svc:
    image: lyyhua/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7006:80
    depends_on:
      - rabbitmq
  gateway-svc:
    image: lyyhua/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
  # web-app:
  #   image: lyyhua/web-app
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   volumes:
  #     - /var/lib/web/data
  #   environment:
  #     - AUTH_SECRET="SYCIOQP2K2eKUDxAIBretRvpFd0rrz3LwcIxunux300="
  #     - AUTH_URL=http://localhost:3000
  #     - AUTH_URL_INTERNAL=http://web-app:3000
  #     - API_URL=http://gateway-svc/
  #     - ID_URL=http://localhost:5000
  #     - ID_URL_INTERNAL=http://identity-svc
  #     - NOTIFY_URL=http://localhost:6001/notifications